
import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import { useRouter } from 'next/router'
import Account from '../components/Account'
import Layout from '../components/Layout.js'

const Connection = () => {
  const session = useSession()
  const supabase = useSupabaseClient()
  const router = useRouter()
  // if(session) router.push('/')

  return (
    <Layout>
    <div className="py-4 lg:py-16 px-20 mx-auto max-w-screen-md">
      {!session ? (
        <Auth 
          supabaseClient={supabase} 
          appearance={{ theme: ThemeSupa }} 
          theme="dark" 
          providers={['github', 'google', 'twitter']}
          />
      ) : (
        <Account session={session} />
      )}
    </div>
    </Layout>
  )
}

export default Connection




// import { useRouter } from 'next/router'
// import { useContext } from 'react'
// import { useSupabaseClient } from '@supabase/auth-helpers-react'
// import Head from 'next/head'
// import { Auth, ThemeSupa } from '@supabase/auth-ui-react'
// import Layout from '../components/Layout.js'
// import UserContext from '../components/UserContext'

// export default function Contact() {
//   const { user } = useContext(UserContext)
//   const router = useRouter()
//   const supabaseClient = useSupabaseClient()
//   if(user) router.push('/profile')
//   return (
//     <Layout>
//       <Head>
//         <title>WebTech - user signin</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="py-4 lg:py-16 px-4 mx-auto max-w-screen-md">
//       <Auth
//         supabaseClient={supabaseClient}
//         appearance={{ theme: ThemeSupa }}
//         providers={['github', 'google', 'twitter']}
//        />
//       </div>
//     </Layout>
//   )
// }
